[workspace]
resolver = "2"
members = [
    "crates/meilisearch",
    "crates/meilitool",
    "crates/meilisearch-types",
    "crates/meilisearch-auth",
    "crates/meili-snap",
    "crates/index-scheduler",
    "crates/dump",
    "crates/file-store",
    "crates/permissive-json-pointer",
    "crates/milli",
    "crates/filter-parser",
    "crates/flatten-serde-json",
    "crates/json-depth-checker",
    "crates/benchmarks",
    "crates/fuzzers",
    "crates/tracing-trace",
    "crates/xtask",
    "crates/build-info",
]

[workspace.package]
version = "1.11.0"
authors = [
    "Quentin de Quelen <quentin@dequelen.me>",
    "Clément Renault <clement@meilisearch.com>",
]
description = "Meilisearch HTTP server"
homepage = "https://meilisearch.com"
readme = "README.md"
edition = "2021"
license = "MIT"

[profile.release]
codegen-units = 1

[profile.dev.package.flate2]
opt-level = 3

[profile.dev.package.grenad]
opt-level = 3
[profile.dev.package.roaring]
opt-level = 3

[profile.dev.package.lindera-ipadic-builder]
opt-level = 3
[profile.dev.package.encoding]
opt-level = 3
[profile.dev.package.yada]
opt-level = 3

[profile.release.package.lindera-ipadic-builder]
opt-level = 3
[profile.release.package.encoding]
opt-level = 3
[profile.release.package.yada]
opt-level = 3

[profile.bench.package.lindera-ipadic-builder]
opt-level = 3
[profile.bench.package.encoding]
opt-level = 3
[profile.bench.package.yada]
opt-level = 3
